### ISSUE TITLE
ld is required by python.ctypes.util.find_library

### ISSUE THREAD

**Issue by codingjoe** [heroku/stack-images#118]
ld is required by Python's `ctypes.util.find_library`

`ld` is part of `binutils-common` and currently only available in build images not runtime.

**Comment by dzuelke** [comment]
Hmmh... `ld` is part of `binutils`, and that program is available at runtime on all stacks. It resides in `/usr/bin`. It looks like the specific problem you're seeing with Django has some other cause.

**Comment by codingjoe** [comment]
@dzuelke the problem was caused by the missing binutils, I am certain of it. However `binutils` have been added 2 month ago, hence resolving the problem. Seealso 03b38d7a5f0bf3d20bef5ab08fb466f4e7f76306
