### ISSUE TITLE
ImageMagick "area" resource limit should be in pixels ?

### ISSUE THREAD

**Issue by MathieuDerelle** [heroku/stack-images#203]
it is currently defined in bytes
https://github.com/heroku/stack-images/blob/e65a994d5540840ebf173528875db4bad5b29467/heroku-18/setup.sh#L213

the documentation is not really clear https://imagemagick.org/script/resources.php

but it looks like that memory/disk resources expect "bytes" and height/width/area expect "pixels"

> Define arguments for the MAGICK_MEMORY_LIMIT, MAGICK_DISK_LIMIT, and MAGICK_MEMORY_LIMIT environment variables with SI prefixes (.e.g 100MB). MAGICK_WIDTH_LIMIT, MAGICK_HEIGHT_LIMIT and MAGICK_AREA_LIMIT accepts pixel suffixes such as MP for mega-pixels (e.g. 100MP)

which would make more sense

**Comment by dzuelke** [comment]
Fixed in #209 for heroku-22

**Comment by edmorley** [comment]
See:
https://github.com/heroku/stack-images/pull/185#issuecomment-1143478370
