### ISSUE TITLE
env PYTHONHOME trigger import error

### ISSUE THREAD

**Issue by Yemacs** [heroku/stack-images#243]
ubuntu 18.04, container env PYTHONHOME  trigger  error

apt-get install xvfb 

unset PYTHONHOME ,  normal

**Comment by edmorley** [comment]
@Yemacs Hi! Heroku does not ship a container image like that - it seems that is a custom image you have created, that uses [heroku-buildpack-python](https://github.com/heroku/heroku-buildpack-python) outside of the Heroku build system - and notably, executes the buildpack's `profile.d/` scripts in a global context (which sets `PYTHONHOME` as you've observed).

Could you explain more about your use-case, and where that image came from?

Also, Ubuntu 18.04 is EOL and insecure - it should not be used any more.
