### ISSUE TITLE
ubuntu-debootstrap is now deprecated

### ISSUE THREAD

**Issue by ericmarcos** [heroku/stack-images#28]
Your Dockerfile depends on ubuntu-debootstrap image which is now deprecated, see:
https://hub.docker.com/_/ubuntu-debootstrap/

**Comment by tt** [comment]
Thank you for reporting this.

The script we run to build our Docker image will [update and upgrade packages](https://github.com/heroku/stack-images/blob/69792c6b1766518da35fe2e0495eec75d59fa691/bin/cedar-14.sh#L85-L86) so it's not currently a problem that it has been deprecated.

It is something we're going to consider when we start work on our next stack image. (It already was for other reasons.)
