### ISSUE TITLE
a couple errors when building

### ISSUE THREAD

**Issue by jjb** [heroku/stack-images#31]
I encountered a couple error messages when building, not sure if they are expected or not.

The output of `sudo /vagrant/bin/capture-stack foo` looked good, but then at the end:

```
-----> Cleaning up. Logs at /tmp/log/capture-stack.log
       umount: /tmp/cedar64-foo: not mounted
```

The output of `sudo /vagrant/bin/install-stack /tmp/cedar64-foo.img.gz` looked good, but then at the end:

```
-----> Mounting image /mnt/stacks/cedar64-foo
/mnt/stacks/cedar64-foo.img: No such file or directory
```

**Comment by dmathieu** [comment]
The commands are relying on each other. What are you executing exactly?

**Comment by jjb** [comment]
the recipe from the readme. i'll close this, as #30 suggests that this project isn't for me anyway :)
