### ISSUE TITLE
Update Deprecated Ruby Version

### ISSUE THREAD

**Issue by amingilani** [heroku/stack-images#43]
[Ruby 1.9.3 reached End of Life in 2015](https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/), consider updating.

**Comment by tt** [comment]
Our Cedar-14 stack image is based on Ubuntu 14.04 LTS and installs default packages. Canonical will maintain those until 2019. We don't replace packages as that might compromise compatibility and break apps.

Our [supported Ruby runtimes](https://devcenter.heroku.com/articles/ruby-support#supported-runtimes) include all recent versions. You'll get one of these whenever the Ruby buildpack is responsible for building your app. The stack image version is only relevant when you're using another language and occasionally shells out for, say, scripting purposes.
