### ISSUE TITLE
Heroku-16 build failing on Docker Hub

### ISSUE THREAD

**Issue by edmorley** [heroku/stack-images#57]
The last set of builds on https://hub.docker.com/r/heroku/heroku/builds/ failed, with error:
```
fatal: Remote branch heroku-16 not found in upstream origin
```

The "Branch" and "Dockerfilefile Location" settings on the Docker Hub Build Settings page need updating ([docs](https://docs.docker.com/docker-hub/builds/)) after #53.

Whilst on Docker Hub, I don't suppose the Cedar-14 image ([here](https://hub.docker.com/r/heroku/cedar/builds/)) could be fixed to point to this repo rather than the tt/stack-images fork, so it picks up updates too? 

Many thanks :-)

**Comment by tt** [comment]
I reconfigured it to use the master branch.

It's not currently possible to change the repository association but I certainly plan to do so when the feature becomes available.

**Comment by edmorley** [comment]
Ah yes I now see docker/hub-feedback#313 about not being able to change the GitHub repo link.

Many thanks for fixing heroku-16 :-)
