### ISSUE TITLE
Docker automated build errors due missing branch

### ISSUE THREAD

**Issue by luislavena** [heroku/stack-images#60]
Hello folks,

Thank you for making the images available to everybody!

I noticed that recent merges and changes to the stack configuration are failing:

https://hub.docker.com/r/heroku/heroku/builds/

```
Building in Docker Cloud's infrastructure...
Cloning into '.'...

warning: Could not find remote branch heroku-16 to clone.

fatal: Remote branch heroku-16 not found in upstream origin

Unexpected end of command stream

please ensure the remote branch exists (128)
```

I'm not sure if that branch ever existed, but will be great if the automated builds can be updated to pick up the changes from `master` instead, now that it contains both `16` and `16-build` Dockerfiles.

Once again, thank you for your work! :heart: :heart: :heart:

**Comment by luislavena** [comment]
Duplicate of #57, closing it.

Apologies for the noise.

**Comment by edmorley** [comment]
[Usual "I'm not an employee disclaimer"]

Yeah the build settings were updated in #57, however there hasn't been a manual retrigger or a push to master since. The latter will hopefully occur with #59, so a manual retrigger is likely not worth it at this point.

**Comment by luislavena** [comment]
Appreciate the comment and the update @edmorley, even with the _disclaimer_ :wink: 

Thank you for the update and have a nice weekend!
