### ISSUE TITLE
'heroku:16-build' isn't automatically rebuilt when 'heroku:16' changes

### ISSUE THREAD

**Issue by edmorley** [heroku/stack-images#67]
Looking at the Docker hub [build details page](https://hub.docker.com/r/heroku/heroku/builds/), the `heroku/heroku:16` image was built 11 days ago, however no corresponding `heroku/heroku:16-build` run was triggered.

I believe this is because Docker Hub's automated builds try and be helpful, and only watch for changes to the specific directory that the automated build points at (and in this case, only the `heroku-16/` directory changed).

To fix this, the Docker hub [repository links](https://docs.docker.com/docker-hub/builds/#repository-links) feature can be used, such that any changes in the `heroku/heroku:16` will trigger a `heroku/heroku:16-build` build too. 

If it's not already set up, it's also worth similarly linking `ubuntu:16.04` to `heroku/heroku:16`, so that any upstream Ubuntu image changes (eg for security fixes) get automatically picked up in the Heroku-16 Docker images. (And same for `ubuntu-debootstrap:14.04` -> `cedar-14`.)

@tt, I don't suppose you could take a look? :-)

**Comment by tt** [comment]
I have tried before but I haven't been able to configure the link between them because they're essentially the same repository. If you figure out how to do this, please let me know.

I'm also considering turning off automatic builds. We want the Docker image to be an exact copy of what's running on Heroku so it's better for us to build once and manually push to Docker Hub.

**Comment by edmorley** [comment]
Ah right. I don't currently have any automated builds of my own on Docker Hub so haven't been able to experiment.

> I'm also considering turning off automatic builds. We want the Docker image to be an exact copy of what's running on Heroku so it's better for us to build once and manually push to Docker Hub.

Yeah I think this makes a lot of sense.

**Comment by tt** [comment]
I'm going to close this. It's not possible using the automated build feature and we have plans to eventually turn that off entirely.
