### ISSUE TITLE
Enable Travis cron and notifications features

### ISSUE THREAD

**Issue by edmorley** [heroku/stack-images#82]
As found in the recent stack image updates, the base Ubuntu docker image can sometimes change in a way that causes breakage unrelated to commits in this repo (eg fewer installed-by-default packages). Whilst this repo now has a Travis run for validating the build and installed package list, it is only triggered by pushes to master, so the most recent job can be showing as green even if a rebuild now might not be.

I was thinking it might be good to enable the Travis cron feature to trigger a extra builds on master once a {day, week, month} so problems can be identified prior to having to do an urgent release when new package CVEs are announced. This could be combined with the Travis notification system (email, IRC, slack, ...) to avoid having to remember to check the Travis status periodically.

For more details, see:
https://docs.travis-ci.com/user/cron-jobs/
https://docs.travis-ci.com/user/notifications/

**Comment by dmathieu** [comment]
Thank you for the suggestion @edmorley, it's a very good idea.
I've enabled weekly runs for the master branch (if there's been no other build in the past 24h).

As for notifications, we already have them internally, based on GitHub commit status.
Travis properly updates the commit status when running a cron job. So we'll be notified of failures.

cc @heroku/build
