### ISSUE TITLE
Stack image roll for git CVEs

### ISSUE THREAD

**Issue by bacongobbler** [heroku/stack-images#83]
Hey there!

Heroku's cedar stack images are vulnerable to [USN-3438-1](https://usn.ubuntu.com/usn/usn-3438-1/). https://devcenter.heroku.com/articles/stack-packages notes that `dpkg --list git` shows `1:1.9.1-1ubuntu0.6`. `1:1.9.1-1ubuntu0.7` contains the fix for USN-3438-1. This affects users of the `heroku/cedar:14` image.

https://github.com/search?q=FROM+heroku%2Fcedar%3A14&type=Code&utf8=%E2%9C%93

**Comment by dmathieu** [comment]
Matthew,

After discussing this with our security team, we're going to consider this as low urgency.
Our GIT server doesn't run `cvssserver`, and the only way apps could be impacted would be if they were running that daemon inside a dyno, which they wouldn't be able to consume from the outside, as our router only handles HTTP.
Therefore, even though this CVE exists, impact on our platform very low to null.

We still need to roll new images for #81 though. The effect of doing so will be that git will be patched too.
This should happen in the next few weeks.

cc @heroku/build @heroku/security

**Comment by kingdonb** [comment]
Watching for updates

Thanks for following up

**Comment by dmathieu** [comment]
The stack image has been rolled.
See https://devcenter.heroku.com/changelog-items/1312
