### ISSUE TITLE
USN-3464-1: Wget vulnerabilities

### ISSUE THREAD

**Issue by stuszynski** [heroku/stack-images#84]
Hi!

Both Cedar nad Heroku stack images are vurnable to [usn-3464-1](https://usn.ubuntu.com/usn/usn-3464-1/). `wget` package should be upgraded to: 

```
Ubuntu 16.04 LTS - heroku/heroku:16
  wget 1.17.1-1ubuntu1.3
Ubuntu 14.04 LTS - heroku/cedar:14
  wget 1.15-1ubuntu1.14.04.3
```

**Comment by ojacobson** [comment]
Hi! Thanks for bringing this to our attention. I've notified our security team; we'll release an update shortly.

**Comment by tt** [comment]
This is done.
